CREATE DATABASE smvecdb;
SHOW DATABASES;

CREATE TABLE EMPLOYEE(ID INT(32), NAME TEXT(23), MARKS INT(34));

INSERT INTO EMPLOYEE VALUES(111,"Dhaneshvar",86);
INSERT INTO EMPLOYEE (id,NAME) VALUES(222,"balu");
SELECT *FROM EMPLOYEE;
SELECT *FROM EMPLOYEE WHERE id=111;

UPDATE EMPLOYEE SET NAME="Ganeshvar" WHERE id=111
DELETE FROM EMPLOYEE WHERE id=222
INSERT INTO EMPLOYEE VALUES(223,"sunil",6)
UPDATE EMPLOYEE SET NAME="Mohan",MARKS=87 WHERE id=222

DELETE FROM EMPLOYEE;
DROP TABLE EMPLOYEE;
DESC EMPLOYEE;
CREATE TABLE EMPLOYEE (id INT(12), NAME TEXT(34),MARKS INT(12));
DROP DATABASE smvecdb;